In [ ]:
import psycopg2
import pandas as pd
import getpass
from sqlalchemy import create_engine

DB_CONFIG = {
    "host": "192.168.100.2",        # 或 127.0.0.1
    "port": 5432,
    "database": "production_db",
    "user": "postgres",
    "password": "SkSB1660"   # 替换成你当初设置的密码
}

conn = psycopg2.connect(**DB_CONFIG)
cur = conn.cursor()
print("✅ 数据库连接成功！")

In [ ]:
# 查看当前库中的所有表以及索引
cur.execute("""
    SELECT table_name 
    FROM information_schema.tables 
    WHERE table_schema='public' 
    ORDER BY table_name;
""")
tables = cur.fetchall()
print("📋 当前数据库中的表：")
for t in tables:
    print(f"  - {t[0]}")

cur.execute("""
    SELECT indexname 
    FROM pg_indexes 
    WHERE schemaname='public' 
    ORDER BY indexname;
""")
indexes = cur.fetchall()
print(f"\n📌 当前索引列表（共 {len(indexes)} 个）：")
for idx in indexes:
    print(f"  - {idx[0]}")

In [5]:
# 查看所有的表

# 1. 获取 public 下所有用户表（排除系统表）
cur.execute("""
    SELECT table_name 
    FROM information_schema.tables 
    WHERE table_schema = 'public' 
      AND table_type = 'BASE TABLE'
    ORDER BY table_name;
""")
tables = cur.fetchall()

print(f"📋 共找到 {len(tables)} 个表\n")

# 2. 逐个遍历并展示
for (table_name,) in tables:
    print("=" * 80)
    print(f"📊 表名: {table_name}")
    
    # 2.1 查询总行数
    cur.execute(f'SELECT COUNT(*) FROM "{table_name}";')
    count = cur.fetchone()[0]
    print(f"📈 总行数: {count}")
    
    # 2.2 查询表结构（字段名和类型）
    cur.execute("""
        SELECT column_name, data_type 
        FROM information_schema.columns 
        WHERE table_name = %s 
        ORDER BY ordinal_position;
    """, (table_name,))
    columns_info = cur.fetchall()
    cols_str = ", ".join([f"{col} ({dtype})" for col, dtype in columns_info])
    print(f"📝 字段结构: {cols_str}")
    
    # 2.3 如果有数据，展示前 5 行
    if count > 0:
        df = pd.read_sql_query(f'SELECT * FROM "{table_name}";', conn)
        print(f"📋 示例数据 (前 5 行):")
        display(df)
    else:
        print("⚠️  该表暂无数据")
    
    print("\n")  # 空行分隔

📋 共找到 10 个表

================================================================================
📊 表名: battery_unit
📈 总行数: 9
📝 字段结构: ID (character varying), PO_ID (integer)
📋 示例数据 (前 5 行):

C:\Users\LiewChuanNyen\AppData\Local\Temp\ipykernel_30208\3269659500.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f'SELECT * FROM "{table_name}";', conn)

      ID  PO_ID
0  S0001      1
1  S0002      1
2  S0003      1
3  S0004      1
4  S0005      3
5  S0006      1
6  S0007      3
7  S0008      5
8  S0009      6

================================================================================
📊 表名: bc_grouping
📈 总行数: 0
📝 字段结构: ID (character varying), Battery_Unit_ID (character varying), Part_ID (character varying)
⚠️  该表暂无数据


================================================================================
📊 表名: bs_result
📈 总行数: 9
📝 字段结构: ID (integer), Employee_ID (integer), Unit_ID (character varying), Produced_Time (timestamp without time zone), Voltage (numeric), Voltage_Max (numeric), Voltage_Min (numeric), Voltage_Mean (numeric), Voltage_Range (numeric), Voltage_SD (numeric), Voltage_CV (numeric), Resistance (numeric), Resistance_Max (numeric), Resistance_Min (numeric), Resistance_Mean (numeric), Resistance_Range (numeric), Resistance_SD (numeric), Resistance_CV (numeric)
📋 示例数据 (前 5 行):

C:\Users\LiewChuanNyen\AppData\Local\Temp\ipykernel_30208\3269659500.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f'SELECT * FROM "{table_name}";', conn)

,ID,Employee_ID,Unit_ID,Produced_Time,Voltage,Voltage_Max,Voltage_Min,Voltage_Mean,Voltage_Range,Voltage_SD,Voltage_CV,Resistance,Resistance_Max,Resistance_Min,Resistance_Mean,Resistance_Range,Resistance_SD,Resistance_CV
0,4,1,S0001,2026-08-18 17:30:11,1.412157,1.412247,1.411968,1.412157,0.000280,0.000111,0.000079,16.821844,18.22475,14.186375,16.821844,4.038375,1.647523,0.097939
1,5,1,S0002,2026-08-18 17:32:16,1.412381,1.412390,1.412370,1.412381,0.000020,0.000008,0.000006,17.890875,17.98700,17.825750,17.890875,0.161250,0.067230,0.003758
2,6,1,S0003,2026-08-19 11:02:28,1.411064,1.411210,1.410860,1.411064,0.000350,0.000132,0.000093,14.503371,17.41750,13.313960,14.503371,4.103540,1.687816,0.116374
3,7,1,S0004,2026-08-19 11:20:50,1.411349,1.411520,1.411107,1.411349,0.000413,0.000156,0.000110,17.456500,17.51275,17.381750,17.456500,0.131000,0.054871,0.003143
4,8,1,S0005,2026-08-19 11:22:33,1.411481,1.411592,1.411315,1.411481,0.000277,0.000104,0.000074,16.720937,16.75925,16.645750,16.720937,0.113500,0.044656,0.002671
5,9,1,S0006,2026-08-19 11:26:14,1.411646,1.411717,1.411555,1.411646,0.000163,0.000059,0.000042,15.148438,16.06250,12.736500,15.148438,3.326000,1.398334,0.092309
6,10,1,S0007,2026-08-19 11:34:01,1.411416,1.411503,1.411302,1.411416,0.000200,0.000075,0.000053,16.333125,16.38425,16.276250,16.333125,0.108000,0.039595,0.002424
7,11,1,S0008,2026-08-19 11:34:44,1.411447,1.411565,1.411272,1.411447,0.000293,0.000109,0.000077,16.906500,16.95775,16.836750,16.906500,0.121000,0.043872,0.002595
8,12,1,S0009,2026-08-19 11:37:11,1.411859,1.411978,1.411618,1.411859,0.000360,0.000076,0.000054,16.245343,16.63875,13.115600,16.245343,3.523150,0.792572,0.048788

================================================================================
📊 表名: employee
📈 总行数: 7
📝 字段结构: ID (integer), Name (character varying), BS_Access (boolean), PC_Access (boolean), WD_Access (boolean)
📋 示例数据 (前 5 行):

C:\Users\LiewChuanNyen\AppData\Local\Temp\ipykernel_30208\3269659500.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f'SELECT * FROM "{table_name}";', conn)

   ID     Name  BS_Access  PC_Access  WD_Access
0   1       Cy       True       True       True
1   2     Ryan       True      False      False
2   3      Max      False       True      False
3   4      Eva      False      False       True
4   5      Kho       True       True      False
5   6       NS       True      False       True
6   7  Jasmine      False       True       True

================================================================================
📊 表名: part
📈 总行数: 0
📝 字段结构: ID (character varying), Model_ID (character varying)
⚠️  该表暂无数据


================================================================================
📊 表名: pc_result
📈 总行数: 0
📝 字段结构: ID (integer), Employee_ID (integer), Unit_ID (character varying), Check_Time (timestamp without time zone), Result (character varying), Image_Path (character varying)
⚠️  该表暂无数据


================================================================================
📊 表名: product
📈 总行数: 2
📝 字段结构: ID (character varying), Cell_Count (integer), Voltage_Upper_Limit (numeric), Voltage_Lower_Limit (numeric), Resistance_Upper_Limit (numeric), Resistance_Lower_Limit (numeric), Holding_Duration (numeric), Voltage_Range_Threshold (numeric), Voltage_SD_Threshold (numeric), Voltage_COV_Threshold (numeric), Resistance_Range_Threshold (numeric), Resistance_SD_Threshold (numeric), Resistance_COV_Threshold (numeric)
📋 示例数据 (前 5 行):

C:\Users\LiewChuanNyen\AppData\Local\Temp\ipykernel_30208\3269659500.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f'SELECT * FROM "{table_name}";', conn)

,ID,Cell_Count,Voltage_Upper_Limit,Voltage_Lower_Limit,Resistance_Upper_Limit,Resistance_Lower_Limit,Holding_Duration,Voltage_Range_Threshold,Voltage_SD_Threshold,Voltage_COV_Threshold,Resistance_Range_Threshold,Resistance_SD_Threshold,Resistance_COV_Threshold
0,BATTERY,28,99.0,-99.0,99.0,-99.0,2.0,99.0,99.0,99.0,99.0,99.0,99.0
1,UPSBUBC4,4,99.0,-99.0,99.0,-99.0,2.0,99.0,99.0,99.0,99.0,99.0,99.0

================================================================================
📊 表名: product_order
📈 总行数: 7
📝 字段结构: ID (integer), Product_ID (character varying), WO_ID (character varying), Total (integer), Remaining (integer)
📋 示例数据 (前 5 行):

C:\Users\LiewChuanNyen\AppData\Local\Temp\ipykernel_30208\3269659500.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f'SELECT * FROM "{table_name}";', conn)

   ID Product_ID   WO_ID  Total  Remaining
0   4    BATTERY  WO0002      6          6
1   7   UPSBUBC4  WO0004     22          0
2   8    BATTERY  WO0004      4          4
3   1   UPSBUBC4  WO0001     10          5
4   3   UPSBUBC4  WO0002      5          3
5   5   UPSBUBC4  WO0003      3          0
6   6    BATTERY  WO0003      6          0

================================================================================
📊 表名: wd_result
📈 总行数: 0
📝 字段结构: ID (integer), Employee_ID (integer), Unit_ID (character varying), Produced_Time (timestamp without time zone), Welding_Axis_X (numeric), Welding_Axis_Y (numeric), Welding_Axis_Z (numeric), Welding_Axis_R (numeric), Welding_Time (numeric), Peak_Voltage (numeric), Average_Voltage (numeric), Peak_Current (numeric), Average_Current (numeric), Power (numeric), Resistance (numeric)
⚠️  该表暂无数据


================================================================================
📊 表名: work_order
📈 总行数: 4
📝 字段结构: ID (character varying), Status (character varying)
📋 示例数据 (前 5 行):

C:\Users\LiewChuanNyen\AppData\Local\Temp\ipykernel_30208\3269659500.py:38: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(f'SELECT * FROM "{table_name}";', conn)

       ID    Status
0  WO0001  On-going
1  WO0002  On-going
2  WO0003  On-going
3  WO0004  On-going

In [ ]:
# Input Employee details
name = input("Employee name:")
bs_access = True if input("BS Access (True/False):").lower() in ['1', 'true', 't', 'yes', 'y'] else False
pc_access = True if input("PC Access (True/False):").lower() in ['1', 'true', 't', 'yes', 'y'] else False
wd_access = True if input("WD Access (True/False):").lower() in ['1', 'true', 't', 'yes', 'y'] else False
cur.execute('INSERT INTO "employee" ("Name", "BS_Access", "PC_Access", "WD_Access") VALUES (%s, %s, %s, %s) RETURNING "ID";', (name, bs_access, pc_access, wd_access))
conn.commit()  # 提交事务
new_id = cur.fetchone()[0]
print(f"✅ New employee inserted, automatically generated ID is: {new_id}")

In [ ]:
# Input Product details
id = input("Product ID:")
cell_count = int(input("Cell Count:"))
voltage_upper_limit = float(input("Voltage Upper Limit:"))
voltage_lower_limit = float(input("Voltage Lower Limit:"))
resistance_upper_limit = float(input("Resistance Upper Limit:"))
resistance_lower_limit = float(input("Resistance Lower Limit:"))
holding_duration = float(input("Holding Duration:"))
voltage_range_threshold = float(input("Voltage Range Threshold:"))
voltage_sd_threshold = float(input("Voltage SD Threshold:"))
voltage_cov_threshold = float(input("Voltage CoV Threshold:"))
resistance_range_threshold = float(input("Resistance Range Threshold:"))
resistance_sd_threshold = float(input("Resistance SD Threshold:"))
resistance_cov_threshold = float(input("Resistance CoV Threshold:"))
cur.execute('INSERT INTO "product" ("ID", "Cell_Count", "Voltage_Upper_Limit", "Voltage_Lower_Limit", "Resistance_Upper_Limit", "Resistance_Lower_Limit", "Holding_Duration", "Voltage_Range_Threshold", "Voltage_SD_Threshold", "Voltage_COV_Threshold", "Resistance_Range_Threshold", "Resistance_SD_Threshold", "Resistance_COV_Threshold") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "ID";', (id, cell_count, voltage_upper_limit, voltage_lower_limit, resistance_upper_limit, resistance_lower_limit, holding_duration, voltage_range_threshold, voltage_sd_threshold, voltage_cov_threshold, resistance_range_threshold, resistance_sd_threshold, resistance_cov_threshold))
conn.commit()
print(f"✅ New product inserted.")

In [ ]:
# Input Work Order details
name = input("Work Order ID:")
status = input("Status:")
cur.execute('INSERT INTO "work_order" ("ID", "Status") VALUES (%s, %s) RETURNING "ID";', (name, status))
conn.commit()
new_id = cur.fetchone()[0]
print(f"✅ New work order inserted.")

In [ ]:
# Input Product Order details
product_id = input("Product ID:")
work_order_id = input("Work Order ID:")
total = input("Total:")
remaining = input("Remaining:")
cur.execute('INSERT INTO "product_order" ("Product_ID", "WO_ID", "Total", "Remaining") VALUES (%s, %s, %s, %s) RETURNING "ID";', (product_id, work_order_id, total, remaining))
conn.commit()
new_id = cur.fetchone()[0]
print(f"✅ New product order inserted.")

In [ ]:
conn.rollback()

In [ ]:
cur.close()
conn.close()